# Generated by Django 6.0.1 on 2026-02-04 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='posts')),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpost', to='core.profile')),
            ],
        ),
    ]
