# Generated by Django 6.0.1 on 2026-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bgimg',
            field=models.ImageField(default='defbgimg.png', upload_to='bgimg'),
        ),
    ]
