# Generated by Django 6.0.1 on 2026-02-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followperson', to='core.profile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.profile')),
            ],
        ),
    ]
