# Generated by Django 6.0.1 on 2026-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
