# Generated by Django 6.0.1 on 2026-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_post_follower_count_post_following_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='following_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
