# Generated by Django 6.0.1 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_github_profile_instagram_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
